title: "Kankakee Community College"
site_name: KCC
public-url: "https://www.kcc.edu"
canonical_baseurl: https://www.kcc.edu # NO trailing slash ## Used to build canonical link elements in document head
port: 3000
theme: "kcc-gem-theme"
timezone: America/Chicago
google-tag_key: GTM-TNVWT2L
core_site: true
core_root: true
humans_file: true
# Jekyll sass configuration options:
sass: # Use jekyll to compile a simple CloudCannon (CC) stylesheet found in `/assets/css/content.scss`
  sass_dir: /assets/scss/ # tell Jekyll where our sass partials are (default is _sass/)
  sourcemap: never # Jekyll command breaks with default sourcemap settings - it's tiny stylesheet anyways
  style: expanded # CC requires an expanded css file for custom CC styles
#translate: true ## Uncomment to activate Google Translate Powers!!
collections:
  contacts:
    output: false
permalink: pretty
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "webpack.config.js"
  - "siteicon.png"
  - "REDIRECTS.web.config"
  - "buildtools/"
  - "postcss.config.js"
  - "look-for-deprecated-bs4-classes.mjs"
  - "look-for-deprecated-bs4-js.mjs"

uploads_dir: "uploads/" # specifies the default uploads directory for CloudCannon

_comments: # Custom hjelper comments/descriptions for CloudCannon
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  description: "Descriptions are seen by search engines like Google and displayed in search results"

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
  translate:
    hidden: true # Prevent CloudCannon Users from randomly turning translate on in their site.
